#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("androidApp.Resource", IsApplication=true)]

namespace androidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int alphaChannelText = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int alphaChannelVisible = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int colorPickerBorderColor = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int colorPickerSliderColor = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int showDialogTitle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int showSelectedColorInList = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int aqua = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public const int black = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int blue = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int def = 2130968592;
			
			// aapt resource value: 0x7f040002
			public const int fuchsia = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int gray = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int green = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int lime = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int maroon = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int navy = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int olive = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int purple = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int red = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int silver = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int teal = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int yellow = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int color_panel_new = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int color_panel_old = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int color_picker_view = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int dialog_color_picker_extra_layout_landscape = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int preference_preview_color_panel = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int switchButton = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ColorPicker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_color_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int preference_preview_layout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060005
			public const int ApplicationName = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int Hello = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int SwitchText = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int dialog_cancle = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int dialog_ok = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int dialog_title = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_color_pciker_view_portrait = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorPickerPreference = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int ColorPickerPreference_showDialogTitle = 0;
			
			// aapt resource value: 1
			public const int ColorPickerPreference_showSelectedColorInList = 1;
			
			public static int[] ColorPickerView = new int[] {
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public const int ColorPickerView_alphaChannelText = 1;
			
			// aapt resource value: 0
			public const int ColorPickerView_alphaChannelVisible = 0;
			
			// aapt resource value: 3
			public const int ColorPickerView_colorPickerBorderColor = 3;
			
			// aapt resource value: 2
			public const int ColorPickerView_colorPickerSliderColor = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
